---
swagger: "2.0"
info:
  version: "2.12"
  title: "ElasTest Device Emulator API"
host: "localhost:8080"
basePath: "/eds"
schemes:
- "https"
- "http"
consumes:
- "application/json"
produces:
- "application/json"
paths:
  /devices:
    get:
      tags:
      - "Device"
      description: "returns all registered devices"
      operationId: "get_devices"
      parameters:
      - name: "deviceName"
        in: "query"
        description: "Zigbee sensor information"
        required: false
        type: "string"
        format: "string"
      responses:
        200:
          description: "All the devices"
          schema:
            type: "array"
            items:
              type: "string"
              format: "uri"
              example: "http://10.0.0.225:8080"
      x-swagger-router-controller: "swagger_server.controllers.device_controller"
    post:
      tags:
      - "Device"
      operationId: "register"
      parameters:
      - in: "body"
        name: "device"
        required: false
        schema:
          $ref: "#/definitions/DeviceRegistrationInfo"
      responses:
        200:
          description: "successfully registered device"
      x-swagger-router-controller: "swagger_server.controllers.device_controller"
  /ZigbeeIPE:
    get:
      tags:
      - "Zigbee"
      operationId: "get_sensor_data"
      parameters:
      - name: "deviceName"
        in: "query"
        description: "name of device exists"
        required: false
        type: "string"
        format: "string"
      responses:
        200:
          description: "ok"
          schema:
            $ref: "#/definitions/ZigbeeIPE"
      x-swagger-router-controller: "swagger_server.controllers.zigbee_controller"
  /MemsIPE:
    get:
      tags:
      - "Mems"
      operationId: "get_memsdata"
      parameters: []
      responses:
        200:
          description: "ok"
          schema:
            $ref: "#/definitions/MemsData"
      x-swagger-router-controller: "swagger_server.controllers.mems_controller"
definitions:
  DeviceRegistrationInfo:
    type: "object"
    properties:
      uri:
        type: "string"
        format: "uri"
        example: "http://10.0.0.220:8080"
      deviceName:
        type: "string"
        format: "string"
        example: "ZBS122S000001"
    example:
      uri: "http://10.0.0.220:8080"
      deviceName: "ZBS122S000001"
  ZigbeeIPE:
    type: "object"
    required:
    - "deviceName"
    properties:
      deviceName:
        type: "string"
        format: "string"
        example: "ZBS122S000001"
      sensor_data:
        $ref: "#/definitions/SensorData"
    example:
      sensor_data:
        brightness:
          t: "2000-01-23T04:56:07.000+00:00"
          u: "lx"
          v: 6.0274563
          lbl: "openmtc:sensor_data"
          n: "brightness"
          nm: "ZBS122S000001"
        temperature:
          t: "2000-01-23T04:56:07.000+00:00"
          u: "cel"
          v: 0.8008282
          lbl: "openmtc:sensor_data"
          n: "brightness"
          nm: "ZBS122S000001"
        humidity:
          t: "2000-01-23T04:56:07.000+00:00"
          u: "%RH"
          v: 5.637377
          lbl: "openmtc:sensor_data"
          n: "brightness"
          nm: "ZBS122S000001"
        pressure:
          t: "2000-01-23T04:56:07.000+00:00"
          u: "hPa"
          v: 1.4658129
          lbl: "openmtc:sensor_data"
          n: "pressure"
          nm: "ZBS122S000001"
        vibration:
          t: "2000-01-23T04:56:07.000+00:00"
          u: "lx"
          v: 2.302136
          lbl: "openmtc:sensor_data"
          n: "vibration"
          nm: "ZBS122S000001"
        movement:
          t: "2000-01-23T04:56:07.000+00:00"
          u: "lx"
          v: 5.962134
          lbl: "openmtc:sensor_data"
          n: "movement"
          nm: "ZBS122S000001"
      deviceName: "ZBS122S000001"
  SensorData:
    type: "object"
    properties:
      temperature:
        $ref: "#/definitions/Temperature"
      brightness:
        $ref: "#/definitions/Brightness"
      pressure:
        $ref: "#/definitions/Pressure"
      movement:
        $ref: "#/definitions/Movement"
      humidity:
        $ref: "#/definitions/Humidity"
      vibration:
        $ref: "#/definitions/Vibration"
    example:
      brightness:
        t: "2000-01-23T04:56:07.000+00:00"
        u: "lx"
        v: 6.0274563
        lbl: "openmtc:sensor_data"
        n: "brightness"
        nm: "ZBS122S000001"
      temperature:
        t: "2000-01-23T04:56:07.000+00:00"
        u: "cel"
        v: 0.8008282
        lbl: "openmtc:sensor_data"
        n: "brightness"
        nm: "ZBS122S000001"
      humidity:
        t: "2000-01-23T04:56:07.000+00:00"
        u: "%RH"
        v: 5.637377
        lbl: "openmtc:sensor_data"
        n: "brightness"
        nm: "ZBS122S000001"
      pressure:
        t: "2000-01-23T04:56:07.000+00:00"
        u: "hPa"
        v: 1.4658129
        lbl: "openmtc:sensor_data"
        n: "pressure"
        nm: "ZBS122S000001"
      vibration:
        t: "2000-01-23T04:56:07.000+00:00"
        u: "lx"
        v: 2.302136
        lbl: "openmtc:sensor_data"
        n: "vibration"
        nm: "ZBS122S000001"
      movement:
        t: "2000-01-23T04:56:07.000+00:00"
        u: "lx"
        v: 5.962134
        lbl: "openmtc:sensor_data"
        n: "movement"
        nm: "ZBS122S000001"
  MemsData:
    type: "object"
    properties:
      x:
        $ref: "#/definitions/X"
      y:
        $ref: "#/definitions/Y"
      z:
        $ref: "#/definitions/Z"
    example:
      x:
        t: "2000-01-23T04:56:07.000+00:00"
        u: "g"
        v: 0.8008282
        lbl: "openmtc:sensor_data"
        bn: "urn:dev1:memsipe"
        n: "x"
      y:
        t: "2000-01-23T04:56:07.000+00:00"
        u: "g"
        v: 6.0274563
        lbl: "openmtc:sensor_data"
        bn: "urn:dev1:memsipe"
        n: "y"
      z:
        t: "2000-01-23T04:56:07.000+00:00"
        u: "g"
        v: 1.4658129
        lbl: "openmtc:sensor_data"
        bn: "urn:dev1:memsipe"
        n: "z"
  Brightness:
    type: "object"
    properties:
      nm:
        type: "string"
        enum:
        - "ZBS122S000001"
        - "ZBS122S000000"
      u:
        type: "string"
        example: "lx"
      v:
        type: "number"
        format: "float"
      t:
        type: "string"
        format: "date-time"
        description: "the timestamp when the brightness was measured"
      n:
        type: "string"
        example: "brightness"
      lbl:
        type: "string"
        example: "openmtc:sensor_data"
        description: "ok"
    example:
      t: "2000-01-23T04:56:07.000+00:00"
      u: "lx"
      v: 6.0274563
      lbl: "openmtc:sensor_data"
      n: "brightness"
      nm: "ZBS122S000001"
  Humidity:
    type: "object"
    properties:
      nm:
        type: "string"
        enum:
        - "ZBS122S000001"
        - "ZBS122S000000"
      u:
        type: "string"
        example: "%RH"
      v:
        type: "number"
        format: "float"
      t:
        type: "string"
        format: "date-time"
        description: "the timestamp when the brightness was measured"
      n:
        type: "string"
        example: "brightness"
      lbl:
        type: "string"
        example: "openmtc:sensor_data"
    description: "ok"
    example:
      t: "2000-01-23T04:56:07.000+00:00"
      u: "%RH"
      v: 5.637377
      lbl: "openmtc:sensor_data"
      n: "brightness"
      nm: "ZBS122S000001"
  Temperature:
    type: "object"
    properties:
      nm:
        type: "string"
        enum:
        - "ZBS122S000001"
        - "ZBS122S000000"
      u:
        type: "string"
        example: "cel"
      v:
        type: "number"
        format: "float"
      t:
        type: "string"
        format: "date-time"
        description: "the timestamp when the brightness was measured"
      n:
        type: "string"
        example: "brightness"
      lbl:
        type: "string"
        example: "openmtc:sensor_data"
    description: "ok"
    example:
      t: "2000-01-23T04:56:07.000+00:00"
      u: "cel"
      v: 0.8008282
      lbl: "openmtc:sensor_data"
      n: "brightness"
      nm: "ZBS122S000001"
  Pressure:
    type: "object"
    properties:
      nm:
        type: "string"
        enum:
        - "ZBS122S000001"
        - "ZBS122S000000"
      u:
        type: "string"
        example: "hPa"
      v:
        type: "number"
        format: "float"
      t:
        type: "string"
        format: "date-time"
        description: "the timestamp when the brightness was measured"
      n:
        type: "string"
        example: "pressure"
      lbl:
        type: "string"
        example: "openmtc:sensor_data"
    description: "ok"
    example:
      t: "2000-01-23T04:56:07.000+00:00"
      u: "hPa"
      v: 1.4658129
      lbl: "openmtc:sensor_data"
      n: "pressure"
      nm: "ZBS122S000001"
  Movement:
    type: "object"
    properties:
      nm:
        type: "string"
        enum:
        - "ZBS122S000001"
        - "ZBS122S000000"
      u:
        type: "string"
        example: "lx"
      v:
        type: "number"
        format: "float"
      t:
        type: "string"
        format: "date-time"
        description: "the timestamp when the brightness was measured"
      n:
        type: "string"
        example: "movement"
      lbl:
        type: "string"
        example: "openmtc:sensor_data"
    description: "ok"
    example:
      t: "2000-01-23T04:56:07.000+00:00"
      u: "lx"
      v: 5.962134
      lbl: "openmtc:sensor_data"
      n: "movement"
      nm: "ZBS122S000001"
  Vibration:
    type: "object"
    properties:
      nm:
        type: "string"
        enum:
        - "ZBS122S000001"
        - "ZBS122S000000"
      u:
        type: "string"
        example: "lx"
      v:
        type: "number"
        format: "float"
      t:
        type: "string"
        format: "date-time"
        description: "the timestamp when the brightness was measured"
      n:
        type: "string"
        example: "vibration"
      lbl:
        type: "string"
        example: "openmtc:sensor_data"
    description: "ok"
    example:
      t: "2000-01-23T04:56:07.000+00:00"
      u: "lx"
      v: 2.302136
      lbl: "openmtc:sensor_data"
      n: "vibration"
      nm: "ZBS122S000001"
  X:
    type: "object"
    properties:
      bn:
        type: "string"
        example: "urn:dev1:memsipe"
        description: "basename of the mems sensor"
      u:
        type: "string"
        example: "g"
      v:
        type: "number"
        format: "float"
      t:
        type: "string"
        format: "date-time"
        description: "the timestamp when the brightness was measured"
      n:
        type: "string"
        example: "x"
      lbl:
        type: "string"
        example: "openmtc:sensor_data"
    description: "ok"
    example:
      t: "2000-01-23T04:56:07.000+00:00"
      u: "g"
      v: 0.8008282
      lbl: "openmtc:sensor_data"
      bn: "urn:dev1:memsipe"
      n: "x"
  Y:
    type: "object"
    properties:
      bn:
        type: "string"
        example: "urn:dev1:memsipe"
        description: "basename of the mems sensor"
      u:
        type: "string"
        example: "g"
      v:
        type: "number"
        format: "float"
      t:
        type: "string"
        format: "date-time"
        description: "the timestamp when the brightness was measured"
      n:
        type: "string"
        example: "y"
      lbl:
        type: "string"
        example: "openmtc:sensor_data"
    description: "ok"
    example:
      t: "2000-01-23T04:56:07.000+00:00"
      u: "g"
      v: 6.0274563
      lbl: "openmtc:sensor_data"
      bn: "urn:dev1:memsipe"
      n: "y"
  Z:
    type: "object"
    properties:
      bn:
        type: "string"
        example: "urn:dev1:memsipe"
        description: "basename of the mems sensor"
      u:
        type: "string"
        example: "g"
      v:
        type: "number"
        format: "float"
      t:
        type: "string"
        format: "date-time"
        description: "the timestamp when the brightness was measured"
      n:
        type: "string"
        example: "z"
      lbl:
        type: "string"
        example: "openmtc:sensor_data"
    description: "ok"
    example:
      t: "2000-01-23T04:56:07.000+00:00"
      u: "g"
      v: 1.4658129
      lbl: "openmtc:sensor_data"
      bn: "urn:dev1:memsipe"
      n: "z"
